name: Test

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yaml"
      - "**.go"
      - "**.go.json"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "Taskfile.yaml"
      - "**.go"
      - "**.go.json"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version: ["~1.22", "~1.23.0-rc.1"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "${{ matrix.go_version }}"

      - run: go test -coverpkg=./... -covermode=atomic -coverprofile=coverage.out -count=1 ./...

      - uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
